# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-02 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chlen_Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chlleny/', verbose_name='\u0421\u04af\u0440\u04e9\u0442')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '\u0427\u043b\u0435\u043d\u044b \u0438 \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u044b',
                'verbose_name_plural': '\u0427\u043b\u0435\u043d\u044b \u0438 \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u044b',
            },
        ),
    ]
