# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-08 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20191008_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofonde',
            name='language',
        ),
        migrations.DeleteModel(
            name='OFonde',
        ),
    ]
