# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-08 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20191008_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='OFonde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(db_index=True, max_length=200, verbose_name='\u0414\u0430\u0440\u0435\u043a')),
                ('phone', models.CharField(db_index=True, max_length=150, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('email', models.EmailField(max_length=254, verbose_name='\u0415\u043c\u0435\u0439\u043b')),
                ('karta', models.CharField(max_length=400, verbose_name='\u041a\u0430\u0440\u0442\u0430')),
                ('facebook', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0424\u0435\u0439\u0441\u0431\u0443\u043a')),
                ('instagram', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0418\u043d\u0441\u0442\u0430\u0433\u0440\u0430\u043c')),
                ('youtube', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u042e\u0442\u0443\u0431')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Language', verbose_name='\u0422\u0438\u043b\u0438')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '\u0410\u0441\u0441\u043e\u0446\u0438\u0430\u0446\u0438\u044f \u0436\u04e9\u043d\u04af\u043d\u0434\u04e9',
                'verbose_name_plural': '\u0410\u0441\u0441\u043e\u0446\u0438\u0430\u0446\u0438\u044f \u0436\u04e9\u043d\u04af\u043d\u0434\u04e9',
            },
        ),
    ]
