# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-10 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_ofonde'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='protsent',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041f\u0440\u043e\u0446\u0435\u043d\u0442 \u043f\u0440\u043e\u0435\u043a\u0442\u0430'),
        ),
    ]
