# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-15 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_new_protsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='glavcategory',
            name='style',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u043a\u043b\u0430\u0441\u0441'),
        ),
    ]
