# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-16 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_glavcategory_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryForKatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='\u0410\u0442\u044b')),
                ('slug', models.CharField(blank=True, max_length=200, verbose_name='\u0422\u0440\u0430\u043d\u0441\u043b\u0438\u0442')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0434\u043b\u044f \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430',
                'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0434\u043b\u044f \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430',
                'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u0434\u043b\u044f \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430',
            },
        ),
        migrations.CreateModel(
            name='GlavCategoryForKatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='\u0410\u0442\u044b')),
                ('slug', models.CharField(blank=True, max_length=200, verbose_name='\u0422\u0440\u0430\u043d\u0441\u043b\u0438\u0442')),
                ('style', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u043a\u043b\u0430\u0441\u0441')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Language', verbose_name='\u0422\u0438\u043b\u0438')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': '\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0434\u043b\u044f \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430',
                'verbose_name': '\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0434\u043b\u044f \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430',
                'verbose_name_plural': '\u0413\u043b\u0430\u0432\u043d\u044b\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u0434\u043b\u044f \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430',
            },
        ),
        migrations.AddField(
            model_name='categoryforkatalog',
            name='glavcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.GlavCategoryForKatalog', verbose_name='\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0434\u043b\u044f \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430'),
        ),
        migrations.AddField(
            model_name='categoryforkatalog',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Language', verbose_name='\u0422\u0438\u043b\u0438'),
        ),
    ]
