# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-26 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_gallery', '0002_remove_album_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='en_name',
            field=models.CharField(max_length=250, null=True, verbose_name='\u0410\u043d\u0433\u043b\u0438\u0441\u0447\u0435 \u0430\u0442\u044b'),
        ),
        migrations.AddField(
            model_name='album',
            name='kg_name',
            field=models.CharField(max_length=250, null=True, verbose_name='\u041a\u044b\u0440\u0433\u044b\u0437\u0447\u0430 \u0430\u0442\u044b'),
        ),
    ]
