# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-26 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_gallery', '0003_auto_20191026_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.AddField(
            model_name='image',
            name='en_description',
            field=models.TextField(blank=True, null=True, verbose_name='\u0410\u043d\u0433\u043b\u0438\u0441\u0447\u0435 \u043c\u0430\u0430\u043b\u044b\u043c\u0430\u0442'),
        ),
        migrations.AddField(
            model_name='image',
            name='kg_description',
            field=models.TextField(blank=True, null=True, verbose_name='\u041a\u044b\u0440\u0433\u044b\u0437\u0447\u0430 \u0430\u0430\u043b\u044b\u043c\u0430\u0442'),
        ),
        migrations.AlterField(
            model_name='image',
            name='ru_description',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u0440\u0443\u0441\u0447\u0430 \u043c\u0430\u0430\u043b\u044b\u043c\u0430\u0442'),
        ),
    ]
