# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-26 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_gallery', '0005_auto_20191026_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='language',
        ),
    ]
